pip install -e Libraries/RZVisuals 
pip install -e Tools/RZCameraExtrinsicsTool 
pip install -e Libraries/RZTrainingPipeline
pip install -e Tools/RZTrainDLC
pip install -e Tools/RZTriangulation
pip install -e Tools/RZCameraCalibration
pip install -e Tools/RZView2DCSV
pip install -e Tools/RZView3DCSV
pip install -e Tools/RZCorrect2D
pip install -e Tools/RZBayesianReconstruction
pip install -e Tools/RZEvaluate
